apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedevnews-db
  labels:
    app: kubedevnews-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedevnews-db
  template:
    metadata:
      labels:
        app: kubedevnews-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "kubedevnews"
        - name: POSTGRES_USER
          value: "kubedevnews"
        - name: POSTGRES_PASSWORD
          value: "Pg#123"
---
apiVersion: v1
kind: Service
metadata:
  name: kubedevnews-db
  labels:
    app: kubedevnews-db
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: kubedevnews-db 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedevnews-app
  labels:
    app: kubedevnews-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedevnews-app
  template:
    metadata:
      labels:
        app: kubedevnews-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: kubedevnews-app
        image: fabriciosveronez/kubedevnews:v1
        ports:
        - containerPort: 5000
        env:
        - name: DB_DATABASE
          value: "kubedevnews"
        - name: DB_USERNAME
          value: "kubedevnews"
        - name: DB_PASSWORD
          value: "Pg#123"
        - name: DB_HOST
          value: "kubedevnews-db"
        - name: DB_PORT
          value: "5432"
        - name: ERROR_RATE_PERCENT
          value: "20"          
---
apiVersion: v1
kind: Service
metadata:
  name: kubedevnews-app
  labels:
    app: kubedevnews-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: kubedevnews-app 
