services:
  app:
    image: fabriciosveronez/kubedevnews:v1
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_DATABASE=kubedevnews
      - DB_USERNAME=kubedevnews
      - DB_PASSWORD=Pg#123
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=kubedevnews
      - POSTGRES_USER=kubedevnews
      - POSTGRES_PASSWORD=Pg#123
    ports:
      - "5432:5432"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - app-network      

networks:
  app-network:
    driver: bridge