global:
  resolve_timeout: 5m
route:
  group_by: ['alertname', severity]
  group_wait: 30s
  repeat_interval: 1h
  receiver: 'webhook-default'

  routes:
    - match:  
        severity: 'critical'
      receiver: 'webhook-critical'

receivers: 
  - name: 'webhook-default'
    webhook_configs:
      - url: ''
  - name: 'webhook-critical'
    webhook_configs:
      - url: ''