global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kube-news'
    static_configs:
      - targets: ['app:5000']
        labels:
          project_name: 'aula-missao-monitoramento'

