global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/rules/alerts.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kube-news'
    static_configs:
      - targets: ['app:5000']
        labels:
          project_name: 'aula-missao-monitoramento'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']